=== ALSETLab/efmi-pss-use-case/Modelica/efMU-FMU-Builds/Exports/eFMUs/PSSTypeII4eFMI/eFMU/schemas/efmiContainerManifest.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:include schemaLocation="efmiModelRepresentationKind.xsd"/>
	<xs:include schemaLocation="efmiIdentifierType.xsd"/>
	<xs:include schemaLocation="efmiManifestAttributes.xsd"/>
	<xs:element name="Content">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="ModelRepresentation" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:attribute name="name" type="efmiNameWithoutSlashesType" use="required">
							<xs:annotation>
								<xs:documentation>Unique name of the container, also defining its root directory (relative to the eFMU's __content.xml).</xs:documentation>
							</xs:annotation>
						</xs:attribute>
						<xs:attribute name="kind" type="ModelRepresentationKind" use="required">
							<xs:annotation>
								<xs:documentation>Type of the container; see enumeration values.</xs:documentation>
							</xs:annotation>
						</xs:attribute>
						<xs:attribute name="manifest" type="efmiNameWithoutSlashesType" use="required">
							<xs:annotation>
								<xs:documentation>Name of the container's manifest file. The manifest is located in the container's root directory, cf. "name" attribute.</xs:documentation>
							</xs:annotation>
						</xs:attribute>
						<xs:attribute name="checksum" type="xs:normalizedString" use="required">
							<xs:annotation>
								<xs:documentation>SHA-1 checksum of the binary content of the container's manifest file.</xs:documentation>
							</xs:annotation>
						</xs:attribute>
						<xs:attribute name="manifestRefId" type="efmiManifestIdentifierType" use="required">
							<xs:annotation>
								<xs:documentation>Like corresponding attribute of ManifestReference. References a manifest using the Manifest element's "id" attribute. Added to speedup resolving references, i.e., only technical purpose.</xs:documentation>
							</xs:annotation>
						</xs:attribute>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="xsdVersion" type="xs:normalizedString" use="required" fixed="0.10.0">
				<xs:annotation>
					<xs:documentation>Version of this schema file in semantic version number format (major.minor.patch) - See VERSION.txt for further information.</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="activeFmu" type="xs:normalizedString">
				<xs:annotation>
					<xs:documentation>Value of name attribute of model representation whose FMU is currently unpacked in the root directory of the container. If no FMU is unpacked currently, the value of this attribute must not be set.</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attributeGroup ref="efmiManifestAttributesBase"/>
		</xs:complexType>
	</xs:element>
	<xs:simpleType name="efmiNameWithoutSlashesType">
		<xs:annotation>
			<xs:documentation>Restrict values to pure names without path slashes in it.
			</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:normalizedString">
			<xs:pattern value="[^/]+"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== ALSETLab/efmi-pss-use-case/Modelica/work/Grid4CHIL_IOplus/eFMU/__content.xml
<?xml version="1.0" encoding="UTF-8"?>
<Content xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsdVersion="0.10.0" efmiVersion="1.0.0" id="{8cb2aafb-1011-4184-9a3b-66482c4c913d}" name="OpenIPSL_CHIL.RTS.CHIL.Grid4CHIL_IOplus" description="System model for CHIL testing with more I/O" version="" generationDateAndTime="2026-03-26T03:53:23Z" generationTool="Dymola Version 2026x Refresh 1 Beta 1, 2026-02-27" xsi:noNamespaceSchemaLocation="./schemas/efmiContainerManifest.xsd">
    <ModelRepresentation name="ACode_Dymola" kind="AlgorithmCode" manifest="manifest.xml" checksum="b737e1c8377190e1e0e899001c2d3de702f2ad02" manifestRefId="{607f1679-ded2-455f-ad0b-fc5f5a4f83cb}"/>
    <ModelRepresentation name="PCode_SPE_cb4a8a449b4ada864625ee5a4355578a3aaf08ed" kind="ProductionCode" manifest="manifest.xml" checksum="78209ff8f34b1a935ef200be2449123c2f21d62c" manifestRefId="{8a87ab11-8105-4fb6-b01c-2cf961715df2}"/>
    <ModelRepresentation name="PCode_SPE_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c" kind="ProductionCode" manifest="manifest.xml" checksum="5df44c583a249986007a9d022f5cc117cc4427e0" manifestRefId="{1d2a990a-5fe3-4f0f-9435-bf1ac945515d}"/>
    <ModelRepresentation name="BCode_SPE_cb4a8a449b4ada864625ee5a4355578a3aaf08ed_121c3a3ad3761b859035224f0aa23f4d834544e7" kind="BinaryCode" manifest="manifest.xml" checksum="1a63c4e8c592311670e9266d645b8ab99c659961" manifestRefId="{a7e1227b-267a-4e7b-885c-bdc9202cde09}"/>
    <ModelRepresentation name="BCode_SPE_cb4a8a449b4ada864625ee5a4355578a3aaf08ed_b48b2d90fa045262ae3c2a0df7ec20da237e1e13" kind="BinaryCode" manifest="manifest.xml" checksum="b49c113eb2e265bfcd868dd7678fd0be0cbd0cf2" manifestRefId="{50393cee-84ed-4718-a447-bc27eafdf49b}"/>
    <ModelRepresentation name="BCode_SPE_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c_121c3a3ad3761b859035224f0aa23f4d834544e7" kind="BinaryCode" manifest="manifest.xml" checksum="2021762fc6ebd793f994c0c7e34f1761a92c1275" manifestRefId="{afe9c7cd-26c1-4659-8b8c-6b890de1e1da}"/>
    <ModelRepresentation name="BCode_SPE_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c_b48b2d90fa045262ae3c2a0df7ec20da237e1e13" kind="BinaryCode" manifest="manifest.xml" checksum="449460f290d623bc04d537f9dd3f042d8b68abe4" manifestRefId="{2e781263-c3f6-4a27-911e-98bb45a78ad6}"/>
</Content>

=== ALSETLab/efmi-pss-use-case/Modelica/efMU-FMU-Builds/eFMUs/PSS/efmuPSS/eFMU/__content.xml
<?xml version="1.0" encoding="UTF-8"?>
<Content xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsdVersion="0.10.0" efmiVersion="1.0.0" id="{813ca981-5613-42b8-8b62-e4ee762cd970}" name="efmiPSSusecase.Components.PSSTypeIImod4efmi" description="Extends the PSS Type II in OpenIPSL with parametrization for eFMI use case" version="" generationDateAndTime="2025-10-27T17:06:18Z" generationTool="Dymola Version 2025x Refresh 1, 2025-04-11" xsi:noNamespaceSchemaLocation="./schemas\efmiContainerManifest.xsd">
    <ModelRepresentation name="ACode_Dymola" kind="AlgorithmCode" manifest="manifest.xml" checksum="7b24c4a4d7f97a5f0a3e58930baa4092492bde96" manifestRefId="{1376699c-b2d8-4069-a285-e4b58ce83b34}"/>
    <ModelRepresentation name="PCode_SPE_cb4a8a449b4ada864625ee5a4355578a3aaf08ed" kind="ProductionCode" manifest="manifest.xml" checksum="31b42af6ffdf815fea4c478065f5a59ddde9a96c" manifestRefId="{53161fae-c40a-422e-8e19-65b0c91dd88b}"/>
    <ModelRepresentation name="PCode_SPE_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c" kind="ProductionCode" manifest="manifest.xml" checksum="db605b72f32e1631badac6a37e2dd06029630f84" manifestRefId="{9d2d5db1-1b0b-4343-b35c-ee1e9d78fb21}"/>
    <ModelRepresentation name="BCode_SPE_cb4a8a449b4ada864625ee5a4355578a3aaf08ed_121c3a3ad3761b859035224f0aa23f4d834544e7" kind="BinaryCode" manifest="manifest.xml" checksum="6147074643da8b9fd411b9ad7df9741150d15294" manifestRefId="{3c08f66c-70f2-456f-9c23-975eac8d0a43}"/>
    <ModelRepresentation name="BCode_SPE_cb4a8a449b4ada864625ee5a4355578a3aaf08ed_b48b2d90fa045262ae3c2a0df7ec20da237e1e13" kind="BinaryCode" manifest="manifest.xml" checksum="e845224c3230798a52d679e02f501b0a9e86d930" manifestRefId="{09e65ae3-98c2-45ab-bb58-4ac5cbe09988}"/>
    <ModelRepresentation name="BCode_SPE_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c_121c3a3ad3761b859035224f0aa23f4d834544e7" kind="BinaryCode" manifest="manifest.xml" checksum="7e8454ac570a796bc90ee8e236c74ae92d15a74f" manifestRefId="{db2c2bda-0bd8-416a-8507-e7136d4eea5a}"/>
    <ModelRepresentation name="BCode_SPE_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c_b48b2d90fa045262ae3c2a0df7ec20da237e1e13" kind="BinaryCode" manifest="manifest.xml" checksum="73c0440ddb3ad03cd67fd47592d3c73b602cb3ec" manifestRefId="{fd811c3b-1c09-4557-8dff-8e46fd545487}"/>
</Content>

=== ALSETLab/efmi-pss-use-case/Modelica/work/Grid4CHILTesting/eFMU/__content.xml
<?xml version="1.0" encoding="UTF-8"?>
<Content xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsdVersion="0.10.0" efmiVersion="1.0.0" id="{ef5003d9-f5df-453d-b40b-8672a93c06fb}" name="PSSDesign.eFMU4CHIL.Grid4CHILTesting" description="System model for CHIL testing" version="" generationDateAndTime="2026-02-27T15:56:46Z" generationTool="Dymola Version 2026x Refresh 1 Beta 1, 2026-02-27" xsi:noNamespaceSchemaLocation="./schemas/efmiContainerManifest.xsd">
    <ModelRepresentation name="ACode_Dymola" kind="AlgorithmCode" manifest="manifest.xml" checksum="6c18713de7d5e3c69c96af11dd21f425b0fc36c7" manifestRefId="{b61d78ad-bf35-4975-9033-902708882880}"/>
    <ModelRepresentation name="PCode_SPE_cb4a8a449b4ada864625ee5a4355578a3aaf08ed" kind="ProductionCode" manifest="manifest.xml" checksum="b801b8f39d04fa25e4a415ffb88ec00a1bd66006" manifestRefId="{0f8d2715-f4ab-455d-9aa5-fb7af245c0b9}"/>
    <ModelRepresentation name="PCode_SPE_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c" kind="ProductionCode" manifest="manifest.xml" checksum="2fb2411cea571e8601f512475d9e7b2d7022607c" manifestRefId="{7a2decfc-5f8d-46ee-a482-c7261e169bf5}"/>
    <ModelRepresentation name="BCode_SPE_cb4a8a449b4ada864625ee5a4355578a3aaf08ed_121c3a3ad3761b859035224f0aa23f4d834544e7" kind="BinaryCode" manifest="manifest.xml" checksum="9dbc28d18122f4f10922080be12171416a6b8a7f" manifestRefId="{877e0c72-c939-47a3-8a32-07b99995ed48}"/>
    <ModelRepresentation name="BCode_SPE_cb4a8a449b4ada864625ee5a4355578a3aaf08ed_b48b2d90fa045262ae3c2a0df7ec20da237e1e13" kind="BinaryCode" manifest="manifest.xml" checksum="f6e215401130af402250a1e6d7be0a8a1a6cd722" manifestRefId="{bf44a4a1-c702-4294-9b48-42b20d69a451}"/>
    <ModelRepresentation name="BCode_SPE_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c_121c3a3ad3761b859035224f0aa23f4d834544e7" kind="BinaryCode" manifest="manifest.xml" checksum="62f3444424eb8674c5b2d392a42e2537a3520e9f" manifestRefId="{64a9487f-0ff5-4894-8c87-83f532f4ba39}"/>
    <ModelRepresentation name="BCode_SPE_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c_b48b2d90fa045262ae3c2a0df7ec20da237e1e13" kind="BinaryCode" manifest="manifest.xml" checksum="43b2d969455e7ca127b394a34ef5d8da61fd88d1" manifestRefId="{13c6b710-6dce-40b3-84b7-59f84cf9ffc3}"/>
	<ModelRepresentation name="BModel_Dymola_d180f6f1e15ef8acfcad8cba73e6b4c1641111e4" kind="BehavioralModel" manifest="manifest.xml" checksum="e772780ae7509f9222c0c06d4dcae4993b3f14df" manifestRefId="{d163c228-89d4-5b13-a05c-2d1b48e52ebc}"/>
</Content>

=== ALSETLab/efmi-pss-use-case/Modelica/work/PSSTypeIISimpleHPF/eFMU/__content.xml
<?xml version="1.0" encoding="UTF-8"?>
<Content xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsdVersion="0.10.0" efmiVersion="1.0.0" id="{98b74a94-240b-44af-be7d-588dab760eb9}" name="OpenIPSL_CHIL.Components.PSS.PSSTypeIISimpleHPF" description="PSS Type II of OpenIPSL with parametrization for eFMI use-case, replacing the derivative filter with a simplified HPF implementation." version="" generationDateAndTime="2026-03-15T04:43:34Z" generationTool="Dymola Version 2026x Refresh 1 Beta 1, 2026-02-27" xsi:noNamespaceSchemaLocation="./schemas/efmiContainerManifest.xsd">
    <ModelRepresentation name="ACode_Dymola" kind="AlgorithmCode" manifest="manifest.xml" checksum="7e9dbf9783e958c649a2c045c271437537eb206f" manifestRefId="{e3edde6d-a095-4d24-9686-6686b1b72b71}"/>
    <ModelRepresentation name="PCode_SPE_cb4a8a449b4ada864625ee5a4355578a3aaf08ed" kind="ProductionCode" manifest="manifest.xml" checksum="75ca1528a73b8c8c167656154a9afb4f0f6f2b49" manifestRefId="{cdcc2da6-18af-4fd7-89b8-d204283ec77e}"/>
    <ModelRepresentation name="PCode_SPE_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c" kind="ProductionCode" manifest="manifest.xml" checksum="054fa0d836c3ff2c4affc2f73e59a6f8f59a3e6b" manifestRefId="{faa97a85-daf4-4303-b230-94bc48264523}"/>
    <ModelRepresentation name="BCode_SPE_cb4a8a449b4ada864625ee5a4355578a3aaf08ed_121c3a3ad3761b859035224f0aa23f4d834544e7" kind="BinaryCode" manifest="manifest.xml" checksum="d52b9b499f6e066c28775c80a1627a6e224e76d7" manifestRefId="{004a1ee9-8b5c-4074-a629-08353afe9052}"/>
    <ModelRepresentation name="BCode_SPE_cb4a8a449b4ada864625ee5a4355578a3aaf08ed_b48b2d90fa045262ae3c2a0df7ec20da237e1e13" kind="BinaryCode" manifest="manifest.xml" checksum="2b0c4bbca243924e23c0a9878c2b6cc6b4d0d11f" manifestRefId="{17fc054e-bc1a-463a-8eba-37b908c42497}"/>
    <ModelRepresentation name="BCode_SPE_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c_121c3a3ad3761b859035224f0aa23f4d834544e7" kind="BinaryCode" manifest="manifest.xml" checksum="494e6a3fea74450f4d7bb816ae92a4ceb74d14c2" manifestRefId="{4e65571f-2a4d-4e61-8078-57ca5fc611ba}"/>
    <ModelRepresentation name="BCode_SPE_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c_b48b2d90fa045262ae3c2a0df7ec20da237e1e13" kind="BinaryCode" manifest="manifest.xml" checksum="e37ee02d2d199583a00083894bb80272098c7d16" manifestRefId="{7f906d5c-2a87-46c2-8ac8-0962653e1523}"/>
	<ModelRepresentation name="BModel_Dymola_1d004974f9b717eea6bd89dae3a804d101968ef8" kind="BehavioralModel" manifest="manifest.xml" checksum="ffad059e990cdf1648a42d1fcb3b3df11e7d5e07" manifestRefId="{aec97202-cf65-dabb-9908-425fb0f97c14}"/>
</Content>

=== ALSETLab/efmi-pss-use-case/Modelica/work/CHILspe/eFMU/__content.xml
<?xml version="1.0" encoding="UTF-8"?>
<Content xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsdVersion="0.10.0" efmiVersion="1.0.0" id="{9f25553f-0445-4894-a7c2-4fc474739d7c}" name="PSSDesign.eFMU4CHIL.Grid4CHILTesting" description="System model for CHIL testing" version="" generationDateAndTime="2026-01-14T21:38:43Z" generationTool="Dymola Version 2026x Refresh 1 Dev 3, 2026-01-23" xsi:noNamespaceSchemaLocation="./schemas\efmiContainerManifest.xsd">
    <ModelRepresentation name="ACode_Dymola" kind="AlgorithmCode" manifest="manifest.xml" checksum="c81c0307c6279283e35adde3ae442086fe44dca6" manifestRefId="{1d85c16f-835a-4842-9bbe-4f71fe66f112}"/>
    <ModelRepresentation name="PCode_SPE_cb4a8a449b4ada864625ee5a4355578a3aaf08ed" kind="ProductionCode" manifest="manifest.xml" checksum="c15c3b865774fea9b7a017dff3d05dfba3d5c3a5" manifestRefId="{b7d34c62-17f3-4f7d-aa91-2e763f8e1773}"/>
    <ModelRepresentation name="PCode_SPE_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c" kind="ProductionCode" manifest="manifest.xml" checksum="a2c358e30aa54a430608e5ed421dfe194f5e2e1b" manifestRefId="{0b09f1bb-c5c8-4693-bddc-e0545535ccf2}"/>
    <ModelRepresentation name="BCode_SPE_cb4a8a449b4ada864625ee5a4355578a3aaf08ed_121c3a3ad3761b859035224f0aa23f4d834544e7" kind="BinaryCode" manifest="manifest.xml" checksum="69772fc6d2caeee0133fd2d672ff8cced2b0c5ac" manifestRefId="{06e58c42-bd96-4010-966b-fb3be9d586a7}"/>
    <ModelRepresentation name="BCode_SPE_cb4a8a449b4ada864625ee5a4355578a3aaf08ed_b48b2d90fa045262ae3c2a0df7ec20da237e1e13" kind="BinaryCode" manifest="manifest.xml" checksum="89e06e15396dca0bd0f90ca7f90a468fa1b06607" manifestRefId="{d3cc1ca3-421d-4fd3-9ad1-c0c7e5ef4e23}"/>
    <ModelRepresentation name="BCode_SPE_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c_121c3a3ad3761b859035224f0aa23f4d834544e7" kind="BinaryCode" manifest="manifest.xml" checksum="0da9fc854de53ace75b22cc85d6099bf5abc335b" manifestRefId="{55d730f4-efee-4176-a951-51c40cefe7cd}"/>
    <ModelRepresentation name="BCode_SPE_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c_b48b2d90fa045262ae3c2a0df7ec20da237e1e13" kind="BinaryCode" manifest="manifest.xml" checksum="7bb988427e8f53225307dc345486a9ab6388ff76" manifestRefId="{ecca49c1-151b-4c5f-ad75-a97d8535d9dd}"/>
</Content>

=== ALSETLab/efmi-pss-use-case/Modelica/efMU-FMU-Builds/Exports/eFMUs/Grid4HIL/eFMU/__content.xml
<?xml version="1.0" encoding="UTF-8"?>
<Content xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsdVersion="0.10.0" efmiVersion="1.0.0" id="{9ee2acd4-d27d-4704-b590-3c28fa53fb49}" name="PSSDesign.eFMUs4RTHIL.GridForHILTesting" description="System model for HIL testing" version="" generationDateAndTime="2025-11-03T22:18:16Z" generationTool="Dymola Version 2025x Refresh 1, 2025-04-11" xsi:noNamespaceSchemaLocation="./schemas\efmiContainerManifest.xsd">
    <ModelRepresentation name="ACode_Dymola" kind="AlgorithmCode" manifest="manifest.xml" checksum="ad8f7fba253328366e5cef1d02b0e071d5b6036e" manifestRefId="{7c3adc9e-74e8-4d94-8d7c-9e9b688cac66}"/>
    <ModelRepresentation name="PCode_SPE_cb4a8a449b4ada864625ee5a4355578a3aaf08ed" kind="ProductionCode" manifest="manifest.xml" checksum="6721c436e00cfdb0033117ecfba9699fbfedfce0" manifestRefId="{bf57db72-e400-4c35-9d0a-ff31736bb4a2}"/>
    <ModelRepresentation name="PCode_SPE_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c" kind="ProductionCode" manifest="manifest.xml" checksum="abe26514af1d66a1c30569276123c3df0b23de78" manifestRefId="{de47d5c5-5ee1-43ba-9603-d213aedff13d}"/>
    <ModelRepresentation name="BCode_SPE_cb4a8a449b4ada864625ee5a4355578a3aaf08ed_121c3a3ad3761b859035224f0aa23f4d834544e7" kind="BinaryCode" manifest="manifest.xml" checksum="997cf45917e9183ac9d04c6e898105feb8ee8346" manifestRefId="{500065f1-1c92-4e03-b4f6-8120da24e7f8}"/>
    <ModelRepresentation name="BCode_SPE_cb4a8a449b4ada864625ee5a4355578a3aaf08ed_b48b2d90fa045262ae3c2a0df7ec20da237e1e13" kind="BinaryCode" manifest="manifest.xml" checksum="036b12b8b14aa20b82b9cdaf683351bf969b4eae" manifestRefId="{f6f833ff-dd0d-450b-90bd-61b23dd9bec9}"/>
    <ModelRepresentation name="BCode_SPE_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c_121c3a3ad3761b859035224f0aa23f4d834544e7" kind="BinaryCode" manifest="manifest.xml" checksum="aa19be92fb06ccc44cac221755623b241bc36fd9" manifestRefId="{0eefa453-af47-41a7-bf49-877fb87def3d}"/>
    <ModelRepresentation name="BCode_SPE_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c_b48b2d90fa045262ae3c2a0df7ec20da237e1e13" kind="BinaryCode" manifest="manifest.xml" checksum="eccda2f8653e16bce08a199a386e9268f009f42e" manifestRefId="{86de149e-b63b-4946-9d7a-7008065e3007}"/>
	<ModelRepresentation name="BModel_Dymola_38088f85a1446bf88ee25daf1830f6a8d82bce99" kind="BehavioralModel" manifest="manifest.xml" checksum="f0b5db12ffd4f19490c8ff1dbe50c04e6b44d0f4" manifestRefId="{ee4c1542-505d-5270-b31f-23e3b59f368b}"/>
</Content>

=== ALSETLab/efmi-pss-use-case/Modelica/work/PSSTypeII4eFMI/eFMU/__content.xml
<?xml version="1.0" encoding="UTF-8"?>
<Content xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsdVersion="0.10.0" efmiVersion="1.0.0" id="{360a7fe8-3f07-4d13-9185-a5ca60359416}" name="PSSDesign.Components.PSSTypeII4eFMI" description="PSS Type II of OpenIPSL with parametrization for eFMI use-case." version="" generationDateAndTime="2026-02-27T16:07:10Z" generationTool="Dymola Version 2026x Refresh 1 Beta 1, 2026-02-27" xsi:noNamespaceSchemaLocation="./schemas/efmiContainerManifest.xsd">
    <ModelRepresentation name="ACode_Dymola" kind="AlgorithmCode" manifest="manifest.xml" checksum="0b1f722a09b535dd17fc3f7cb7eaeeec74cc046b" manifestRefId="{17deebad-9daf-4310-b39a-5076aad6f45b}"/>
    <ModelRepresentation name="PCode_SPE_cb4a8a449b4ada864625ee5a4355578a3aaf08ed" kind="ProductionCode" manifest="manifest.xml" checksum="a81948451fdb6de44c0a58d8b68df81bf1db6f9d" manifestRefId="{b57c201e-46a4-444c-8ba8-e4e75187cd2f}"/>
    <ModelRepresentation name="PCode_SPE_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c" kind="ProductionCode" manifest="manifest.xml" checksum="05392456d0924ee15a7de0f2f74e16546a471f8b" manifestRefId="{be3710c5-03ca-4e2e-b939-393f29cf4f47}"/>
    <ModelRepresentation name="BCode_SPE_cb4a8a449b4ada864625ee5a4355578a3aaf08ed_121c3a3ad3761b859035224f0aa23f4d834544e7" kind="BinaryCode" manifest="manifest.xml" checksum="0ae0f6110d3115b926ef88c9839f5fb025fb9f85" manifestRefId="{6a0f3098-b934-4087-a99c-c8f4c3c1c640}"/>
    <ModelRepresentation name="BCode_SPE_cb4a8a449b4ada864625ee5a4355578a3aaf08ed_b48b2d90fa045262ae3c2a0df7ec20da237e1e13" kind="BinaryCode" manifest="manifest.xml" checksum="e3bc79b00b557ecd33f2d2386873d9ac7cf1acb7" manifestRefId="{0d158377-b80e-4cc8-b359-93a762478f96}"/>
    <ModelRepresentation name="BCode_SPE_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c_121c3a3ad3761b859035224f0aa23f4d834544e7" kind="BinaryCode" manifest="manifest.xml" checksum="b89119c0e9a019eac0d2cca1a35552cd6463e6c5" manifestRefId="{d29c36f6-5c69-4cde-b4bb-a36aa2b3a256}"/>
    <ModelRepresentation name="BCode_SPE_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c_b48b2d90fa045262ae3c2a0df7ec20da237e1e13" kind="BinaryCode" manifest="manifest.xml" checksum="0ed9e5153c3645bc75b6637658c67929351f661b" manifestRefId="{37e6523e-a52b-4a7d-8982-170d9b0f7318}"/>
	<ModelRepresentation name="BModel_Dymola_1cdf13902f8ff1051dd45e29521f833634c3c750" kind="BehavioralModel" manifest="manifest.xml" checksum="b7382398ef33bda9a4a12245e955fd5b81b8afe2" manifestRefId="{99e05f12-2d9b-42e6-b07b-8b6358ec78f9}"/>
</Content>

=== ALSETLab/efmi-pss-use-case/Modelica/efmuPSS/eFMU/__content.xml
<?xml version="1.0" encoding="UTF-8"?>
<Content xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsdVersion="0.10.0" efmiVersion="1.0.0" id="{8a3cb5c5-d6cd-4739-8ffd-40d4ed45b990}" name="efmiPSSusecase.Components.PSSTypeIImod4efmi" description="Extends the PSS Type II in OpenIPSL with parametrization for eFMI use case" version="" generationDateAndTime="2025-10-28T03:07:14Z" generationTool="Dymola Version 2025x Refresh 1, 2025-04-11" xsi:noNamespaceSchemaLocation="./schemas\efmiContainerManifest.xsd">
    <ModelRepresentation name="ACode_Dymola" kind="AlgorithmCode" manifest="manifest.xml" checksum="8d6618e575568248d2c175353ec7fc7bbd026f3d" manifestRefId="{e0dd1bd3-9257-4699-8fb8-3210401074e2}"/>
    <ModelRepresentation name="PCode_SPE_cb4a8a449b4ada864625ee5a4355578a3aaf08ed" kind="ProductionCode" manifest="manifest.xml" checksum="e65ab9848030c763fba4163c1f9d481c48460c63" manifestRefId="{c06b46e1-6d59-4af9-8866-4740ccf69ae4}"/>
    <ModelRepresentation name="PCode_SPE_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c" kind="ProductionCode" manifest="manifest.xml" checksum="66bb5b2734b6ce38e8280c06769f08b23fff0497" manifestRefId="{c94988a2-5a7e-45c0-bec5-d0e40e84213c}"/>
    <ModelRepresentation name="BCode_SPE_cb4a8a449b4ada864625ee5a4355578a3aaf08ed_121c3a3ad3761b859035224f0aa23f4d834544e7" kind="BinaryCode" manifest="manifest.xml" checksum="8e9115e6c30798ed44211d88a7575a1076b18c44" manifestRefId="{798fd7bd-ca51-4810-96f3-033cd52eb27c}"/>
    <ModelRepresentation name="BCode_SPE_cb4a8a449b4ada864625ee5a4355578a3aaf08ed_b48b2d90fa045262ae3c2a0df7ec20da237e1e13" kind="BinaryCode" manifest="manifest.xml" checksum="51872046109a934902cdfd853e043cc452dda1b1" manifestRefId="{50d64050-68d8-4d1e-b68d-014b77b73e06}"/>
    <ModelRepresentation name="BCode_SPE_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c_121c3a3ad3761b859035224f0aa23f4d834544e7" kind="BinaryCode" manifest="manifest.xml" checksum="fd3fa1fc32a9158df9c6e005c2835b1a37e60e38" manifestRefId="{faec7b0a-a280-4c85-a9b2-8d02415593fc}"/>
    <ModelRepresentation name="BCode_SPE_fba3e0dfa6c8985b41bcbe3594ee941ce98b740c_b48b2d90fa045262ae3c2a0df7ec20da237e1e13" kind="BinaryCode" manifest="manifest.xml" checksum="3645f51ef6e34601c4d6f5b9d5ed60b48f159ec7" manifestRefId="{ce4ad299-34c8-4c5f-9359-c246b9ae7ddb}"/>
	<ModelRepresentation name="BModel_Dymola_200c711367943bdee125301112f1e06ff95def82" kind="BehavioralModel" manifest="manifest.xml" checksum="ca9a5f6ad5cdf660318e5ec5f8e7b2ac92c9b11a" manifestRefId="{bf41f1b6-cead-d650-8ded-ce83e4cd1ab8}"/>
</Content>
